#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack
import argparse

parser = argparse.ArgumentParser(description='Strip certain fields from the data.')
parser.add_argument('--fields', type=str, help='A comma-separated list of the field-keys to strip. Example --fields sections,county')
args = parser.parse_args()

if not args.fields:
    sys.stderr.write("Error:   --fields must be specified and contain at least 1 field.\n")
    exit(2);

to_strip = args.fields.split(',')

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
for item in unpacker:

    for field in to_strip:
        if field in item:
            del item[field]

    sys.stdout.write(msgpack.packb(item))
