#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack
import argparse
from curvature.geomath import Units

parser = argparse.ArgumentParser(description='Output a tab-delimited file listing segments.')
parser.add_argument('--units', type=str, default='mi', choices=['mi', 'km'], help='Distance units in the output, km or mi Default: mi')
args = parser.parse_args()

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
sys.stdout = codecs.getwriter('utf8')(sys.stdout)

units = Units(args.units)

sys.stdout.write("Curvature	Length (%s)\tDistance (%s)\tId\tName\tCounty\n" % (args.units, args.units))

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
for item in unpacker:
    sys.stdout.write("%d\t%9.2f\t%9.2f\t%10s\t%25s\t%20s\n" % (item['curvature'], units.convert(item['length']), units.convert(item['distance']), item['id'], item['name'], item['county']))

sys.stdout.write("\n")
