#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import math
import msgpack
import argparse
import pprint
from curvature.geomath import distance_on_earth

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)

parser = argparse.ArgumentParser(description='Filter segments by radius')
parser.add_argument('--min', type=float, help='The minimum radius')
parser.add_argument('--max', type=float, help='The minimum radius')
args = parser.parse_args()

if not args.min and not args.max:
    sys.stderr.write("Error: one or more of [--min, --max] options are required\n")
    exit(2);

def select_segment(segment):
    filter_min = args.min and args.min > segment['radius']
    filter_max = args.max and args.max < segment['radius']
    return not (filter_min or filter_max)

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
for item in unpacker:
    all_segments = item['segments']
    last_index = len(all_segments) - 1
    indexes = [i for i, segment
        in enumerate(all_segments)
        if i == 0 or i == last_index or select_segment(segment)
    ]
    item['segments'] = filtered_segments = [all_segments[i] for i in indexes]
    for i, segment in enumerate(item['segments']):
        if i + 1 < len(item['segments']):
            segment['end'] = end = filtered_segments[i + 1]['start']
            start = segment['start']
            segment['length'] = distance_on_earth(start[0], start[1], end[0], end[1])
    sys.stdout.write(msgpack.packb(item))
