#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack
import argparse

parser = argparse.ArgumentParser(description='Filter out items not meeting our curvature levels.')
parser.add_argument('--min', type=float, default=0, help='The minimum curvature level to be included in the output, e.g. 300, default 0 means no minum')
parser.add_argument('--max', type=float, default=0, help='The maximum curvature level to be included in the output, e.g. 5000, default 0 means no maximum')
args = parser.parse_args()

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
for item in unpacker:
	if item['curvature'] >= args.min and (not args.max or item['curvature'] <= args.max):
		sys.stdout.write(msgpack.packb(item))
