#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
for item in unpacker:
    segments = item['segments']
    # Add the starting point from the first segment.
    points = [(segments[0]['start'][1], segments[0]['start'][0])]
    # Add the ending point from all segments.
    for segment in segments:
        points.append((segment['end'][1], segment['end'][0]))
    item['points'] = points
    sys.stdout.write(msgpack.packb(item))
