#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack
import argparse

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
# sys.stdout = codecs.getwriter('utf8')(sys.stdout)

parser = argparse.ArgumentParser(description='Sort items in the stream')
parser.add_argument('--key', type=str, default='curvature', help='The key to sort on, default: curvature')
parser.add_argument('--direction', type=str, default='DESC', help='The sort direction, ASC or DESC. Default: DESC')
args = parser.parse_args()
if args.direction == 'ASC':
    reverse = False
elif args.direction == 'DESC':
    reverse = True
else:
    sys.stderr.write("\n--direction must be ASC or DESC.")
    exit(2);

unpacker = msgpack.Unpacker(sys.stdin, use_list=True)
items = sorted(unpacker, key=lambda k: k[args.key], reverse=reverse)
for item in items:
    sys.stdout.write(msgpack.packb(item))
