#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import codecs
import msgpack
import pprint

# Set our output to default to UTF-8
reload(sys)
sys.setdefaultencoding('utf-8')
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
sys.stdout = codecs.getwriter('utf8')(sys.stdout)

unpacker = msgpack.Unpacker(use_list=True)
while True:
    data = sys.stdin.read()
    if len(data) == 0:
        break
    unpacker.feed(data)
    for item in unpacker:
        pp = pprint.PrettyPrinter(indent=4)
        pp.pprint(item)
